FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache openssl

COPY package*.json ./
COPY tsconfig.json ./
COPY prisma ./prisma/

RUN npm install
RUN npx prisma generate

EXPOSE 3004

CMD ["sh", "-c", "npx prisma migrate deploy && npm run dev"]
