FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache openssl

COPY package*.json ./
COPY tsconfig.json ./
COPY prisma ./prisma/

RUN npm install

EXPOSE 3002

CMD ["sh", "-c", "npx prisma migrate deploy && npx prisma generate && exec npx tsx watch src/index.ts"]
